version: 0.1
phases:
  install:
    commands:
      - pip install -U awscli pip
      - sudo apt-get update
      - sudo apt-get install -y zip
      - aws --version
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install -r test_requirements.txt
  build:
    commands:
      - flake8
      - py.test -vv
  post_build:
    commands:
      - zip -r packaged/deployment.zip ./app.py
      - aws cloudformation package --template-file packaged/sam.json --s3-bucket ${APP_S3_BUCKET} --output-template-file transformed.yaml
artifacts:
  type: zip
  files:
    - transformed.yaml
